steps:

# Build backend image
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - asia-south1-docker.pkg.dev/$PROJECT_ID/dental-repo/backend:$SHORT_SHA
    - ./Backend

# Push backend image
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - asia-south1-docker.pkg.dev/$PROJECT_ID/dental-repo/backend:$SHORT_SHA

# Build frontend image
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - asia-south1-docker.pkg.dev/$PROJECT_ID/dental-repo/webapp:$SHORT_SHA
    - ./WebApp/dental-care-web

# Push frontend image
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - asia-south1-docker.pkg.dev/$PROJECT_ID/dental-repo/webapp:$SHORT_SHA


# Connect to GKE
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    - container
    - clusters
    - get-credentials
    - dentalk8scluster
    - --region
    - asia-south1


# Apply Kubernetes manifests
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: kubectl
  args:
    - apply
    - -f
    - Kubernetes/
    - -R


# Update backend image
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: kubectl
  args:
    - set
    - image
    - deployment/backend-deployment
    - python-backend=asia-south1-docker.pkg.dev/$PROJECT_ID/dental-repo/backend:$SHORT_SHA


# Update frontend image
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: kubectl
  args:
    - set
    - image
    - deployment/frontend-deployment
    - node-frontend=asia-south1-docker.pkg.dev/$PROJECT_ID/dental-repo/webapp:$SHORT_SHA


options:
  logging: CLOUD_LOGGING_ONLY
