steps:

# Build webapp container
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '-t'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/dental-repo/webapp:$SHORT_SHA'
    - './WebApp/dental-care-web'

# Push container to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/dental-repo/webapp:$SHORT_SHA'


images:
- 'asia-south1-docker.pkg.dev/$PROJECT_ID/dental-repo/webapp:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
